version: '3'

services:
  phoenix:
    build:
        context: .
    env_file:
      - ./env/app.env.dev
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./env/db.env.dev
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: