---
- hosts: application
  vars:
    - packages:
      # Scans system access logs and bans IPs that show malicious signs
      - fail2ban
      # For reverse proxy into our application
      - nginx

  remote_user: root

  tasks:
  - name: install postgres + postgres packages
    apt:
      update_cache: yes
      state: present
      name:
        - postgresql
        - postgresql-contrib
        - libpq-dev

  - name: create postgres user
    postgresql_user:
      name: "{{database_user}}"
      password: "{{database_password}}"
      role_attr_flags: CREATEDB,SUPERUSER
      state: present
    become_user: postgres
    become: yes

  - name: create database
    postgresql_db:
      name: "{{database_name}}"
      encoding: "UTF-8"
    become_user: postgres
    become: yes