---
- hosts: application

  remote_user: root

- name: Configure Machine Login
  import_playbook: playbooks/configure-login.yml

- name: Install Packages
  import_playbook: playbooks/install-packages.yml

- name: Application Deployment Setup
  import_playbook: playbooks/application-deployment-setup.yml

- name: Install Postgres
  import_playbook: playbooks/postgres.yml

- name: Configure Certbot
  import_playbook: playbooks/lets-encrypt.yml

- name: Setup Nginx
  import_playbook: playbooks/nginx.yml